FROM almalinux:9
RUN dnf install nginx -y && \
    rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/DAWS-82S/notes/main/session-43.txt /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]